version: '3.8'

services:
  mysql:
    image: mysql
    container_name: mysql
    ports:
      - 3306:3306
    volumes:
      - ~/apps/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=S3cret
      - MYSQL_PASSWORD=sahebi
      - MYSQL_USER=amir
      - MYSQL_DATABASE=test
    networks:
      - backend_1

  
  redis:
    image: redis:latest
    container_name: redis1
    ports:
        - 6379:6379
    volumes:
        - ./config/redis.conf:/redis.conf
    command: [ "redis-server", "/redis.conf" ]
    networks:
      - backend_1

    
  web:
    build: .
    command: bash -c 'python3 create_db.py && uvicorn main:app --reload --host 0.0.0.0 --port 8000'
    volumes:
      - .:/app
    ports:
      - 8000:8000
    environment:
      - REDIS_HOST=redis1
    depends_on:
      - mysql
      - redis
    networks:
      - backend_1
    restart: on-failure:10
  


networks:
  backend_1:
    driver: bridge
    name: backend_1